# Generated by Django 3.2.12 on 2022-03-21 15:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='заголовок')),
                ('description', models.TextField(verbose_name='описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время добавления')),
                ('deadline', models.DateTimeField(default=datetime.datetime(2022, 3, 23, 15, 49, 30, 601269, tzinfo=utc), verbose_name='дедлайн')),
                ('status', models.CharField(choices=[('done', 'done'), ('not performed', 'not performed')], default='not performed', max_length=15, verbose_name='Статус')),
                ('creator', models.ForeignKey(default=users.models.CustomUser, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
